version: "3"


services:
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - 27022:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: s3cr37
    volumes:
      - "./dump:/dumps"

  mysql:
    image: mysql:latest
    restart: always
    ports:
      - 33010:3306
    environment:
      MYSQL_ROOT_PASSWORD: s3cr37
    volumes:
      - "./scripts/schema.sql:/docker-entrypoint-initdb.d/1.sql"
